### ISSUE TITLE
mhn install fails on linux ubuntu 18.04

### ISSUE THREAD

**Issue by drewnydrzew** [pwnlandia/mhn#804]
Hi 
i am trying install mhn on fresh install of ubuntu 18.04

i got this errors. 

```
Initializing` database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 5, in <module>
    create_clean_db()
  File "/opt/mhn/server/mhn/__init__.py", line 116, in create_clean_db
    db.create_all()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
    self._sa.apply_driver_hacks(self._app, info, options)
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 861, in apply_driver_hacks
    info.database = os.path.join(app.root_path, info.database)
AttributeError: can't set attribute
```

i updated models.py

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

ref.text = r.decode('utf-8')
```

and still error

**Comment by AlSower141** [comment]
Also having the same issue , tried on v14.0.4 also still the same , did you find a fix for this ?

**Comment by Kanchanakkh** [comment]
The version of Flask-SQLAlchemy should be changed to: 2.5.1
Check out the pull request: https://github.com/pwnlandia/mhn/pull/805

**Comment by theJoker141** [comment]
how do i do that ? , sorry in advance only new to this side of stuff , how do i change it ? should it just update with the system ?

**Comment by ridart44** [comment]
I have the same issue. It fixed after i update the version of Flask-SQLAlchemy. You can change the requirements.txt during installing install_mhnserver.sh. To do that, go to your mhn directory, in my case: 
cd /opt/mhn/server
Then, edit the requirements.txt by any editor you like.
sudo nano requirements.txt
change the version of Flask-SQLAlchemy to 2.5.1 and save.
Now you can try to reinstall the mhnserver by running sudo ./install_mhnserver.sh at /opt/mhn/scripts
or reinstall the whole process from the beginning by running sudo ./install.sh at /opt/mhn

Hope this fix your issue,
Thank you

**Comment by theJoker141** [comment]
it fixed it , huge thanks really appreciate it !

**Comment by luctuosa** [comment]
@ridart44 fixed it for me too! thank you <3

**Comment by oliveiralive** [comment]
Hello everyone
The post of the @ridart44 fix here,  

details below

**PROBLEM**
ubuntu 18.4
mhn-celery-worker (Not work)
when i went to http://10.100.20.200 was show 'Welcome to nginx!' :(


root@ubuntu-s-1vcpu-2gb-nyc3-01:/opt/mhn# sudo supervisorctl status
geoloc RUNNING pid 14518, uptime 0:06:38
honeymap RUNNING pid 14519, uptime 0:06:38
hpfeeds-broker RUNNING pid 27699, uptime 0:09:00
mnemosyne RUNNING pid 13582, uptime 0:07:17

root@ubuntu-s-1vcpu-2gb-nyc3-01:/opt/mhn# cd /var/log/mhn/
root@ubuntu-s-1vcpu-2gb-nyc3-01:/var/log/mhn# sudo chown www-data mhn.log
root@ubuntu-s-1vcpu-2gb-nyc3-01:/var/log/mhn# sudo supervisorctl start mhn-celery-worker
mhn-celery-worker: ERROR (no such process)      


**FIXED**
Go on cd /opt/mhn/server
sudo vi requirements.txt
and set Flask-SQLAlchemy==2.5.1
back to /opt/mhn and reinstall whith sudo ./install.sh

Work now

**Comment by malakaisbest** [comment]
Hi all,
I did fresh install  MHN on ubuntu 18.04.4 (followed the instruction on README.md)
but my "honeymap" server is FATAL 
![image](https://user-images.githubusercontent.com/12796396/127055069-589ff069-4804-4e7c-9aeb-3888666b555c.png)
then I tried manual instal "/opt/mhn/scripts/install_honeymap.sh".
but issue is not fixed

**Comment by ridart44** [comment]
Hi Malaka Wickremasinghe, I cannot find your question tag in GitHub, so I try to help your problem with this email. Th issue has ben fixed in issue #305. You can directly check in closed issues #305. According solution provided in the issue above, you can try to run this command:cd /opt/honeymap/serverexport GOPATH=/opt/honeymap/servergo getgo build I hope this fixed your issue. If you have another issue in this MHN that haven’t found in GitHub, you can create a new post there. You also could send me an email for help, I might could help you fix your issue. Thank You, Hary Ridart From: Malaka WickremasingheSent: Tuesday, July 27, 2021 3:34 AMTo: pwnlandia/mhnCc: Hary Ridart; MentionSubject: Re: [pwnlandia/mhn] mhn install fails on linux ubuntu 18.04 (#804) Hi all,I did fresh install MHN on ubuntu 18.04.4 (followed the instruction on README.md)but my "honeymap" server is FATALthen I tried manual instal "/opt/mhn/scripts/install_honeymap.sh".but issue is not fixed—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by malakaisbest** [comment]
Hi Hary Ridart,
thank you very much for this reply.
yes I found that  #305 answer after I post this on Github. that's why I
delete my comment.
I really appreciate your contribution to open-source software.

*Malaka Wickremasinghe*

**Comment by wrharding** [comment]
Fixed in #805
